
services:
  app:
    image: node:24
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  dev:
    image: node:24
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: bash -lc "yarn install && yarn dev"
    ports:
      - "3000:3000"
  preview:
    image: node:24
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: bash -lc "yarn install && yarn build && yarn preview"
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./.output/public:/usr/share/nginx/html:ro
    ports:
      - "8030:80"
    restart: unless-stopped
